### ISSUE TITLE
Create Roadmap for Mobile Object Development

### ISSUE THREAD

**Issue by ikiril01** [CybOXProject/schemas#327]
We should create a "roadmap" or plan for how we wish to tackle the development of mobile-specific CybOX entities. Here's a rough starting point:

* Look into messaging/message object
* Identify Object gaps in CybOX for mobile
* Identify Action gaps in CybOX for mobile
* Take a stab at highlighting the mobile landscape/ecosystem

**Comment by ikiril01** [comment]
Leaving this open for now, but honestly this is so broad that it might be best left as a Wiki page or something other than a tracker item.

**Comment by jonathanbaker** [comment]
I agree, create a road map is not a good fit for an issue. Lets close this and create a wiki page. Once we know what changes we want to make we can open appropriate issues

**Comment by ikiril01** [comment]
Sounds good - I've added a wiki entry here: https://github.com/CybOXProject/schemas/wiki/Roadmap-for-Mobile-related-Support-in-CybOX
