### ISSUE TITLE
Decouple the patterning capabilities of CybOX from the object model

### ISSUE THREAD

**Issue by johnwunder** [CybOXProject/schemas#352]
There have been various suggestions to de-couple the CybOX patterning capabilities from the instance capabilities.

**Comment by gtback** [comment]
:+1:

**Comment by ikiril01** [comment]
Context: this could facilitate the creation of more complex and comprehensive patterns in CybOX and therefore is directly related to #316 and #317. 

LOE: High

**Comment by ikiril01** [comment]
Issue #381 subsumes this one, so I'm closing it.
