### ISSUE TITLE
Decouple file system and file metadata from File object

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/schemas#353]
The `FileObjectType` conflates file system and file metadata which could be decoupled. As there are several derivations of the `FileObjectType`, this change would cascade to other parts of the language.

**Comment by gtback** [comment]
I swore we already had an issue for this. #315 and/or #325?

**Comment by bworrell** [comment]
@gtback, my bad! I didn't look through the issues to see if this was already here. I'm gonna close this :)
