### ISSUE TITLE
Idiom to describe when to use object_reference vs idref

### ISSUE THREAD

**Issue by CyberDaedalus00** [CybOXProject/schemas#393]
There is no idiom or documentation anywhere that explains when one SHOULD use idref versus object_reference when referring to another object.  A good example of this is in the Malicious E-mail indicator with Attachment example in the STIX idioms

**Comment by johnwunder** [comment]
Did you see the writeup in the [suggested practices](http://cyboxproject.github.io/documentation/suggested-practices/#creating-references)?

**Comment by CyberDaedalus00** [comment]
Clearly I missed it. Thanks
